use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug)]
pub enum WasmError {
    Io(std::io::Error),
    R1csError(String),
    BuildFailed(String),
    TemplateError(String),
    CommandFailed(String),
}

impl std::fmt::Display for WasmError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WasmError::Io(e) => write!(f, "IO error: {}", e),
            WasmError::R1csError(msg) => write!(f, "R1CS parsing error: {}", msg),
            WasmError::BuildFailed(msg) => write!(f, "WASM build failed: {}", msg),
            WasmError::TemplateError(msg) => write!(f, "Template generation error: {}", msg),
            WasmError::CommandFailed(msg) => write!(f, "Command execution failed: {}", msg),
        }
    }
}

impl std::error::Error for WasmError {}

impl From<std::io::Error> for WasmError {
    fn from(error: std::io::Error) -> Self {
        WasmError::Io(error)
    }
}

pub struct WasmConfig {
    pub r1cs_path: PathBuf,
    pub output_dir: PathBuf,
    pub circuit_name: String,
}

pub fn generate_witness_calculator(config: WasmConfig) -> Result<(), WasmError> {
    let wasm_dir = config
        .output_dir
        .join(format!("{}_wasm", config.circuit_name.to_lowercase()));

    println!(
        "Generating WASM witness calculator for circuit: {}",
        config.circuit_name
    );
    println!("Output directory: {}", wasm_dir.display());

    create_wasm_crate_structure(&wasm_dir)?;

    let r1cs_data = fs::read(&config.r1cs_path)?;
    validate_r1cs_data(&r1cs_data)?;

    generate_cargo_toml(&wasm_dir, &config.circuit_name)?;
    generate_lib_rs(&wasm_dir, &config.circuit_name)?;
    embed_r1cs_data(&wasm_dir, &r1cs_data)?;
    generate_solver(&wasm_dir)?;
    generate_r1cs_types(&wasm_dir)?;

    build_wasm(&wasm_dir)?;

    generate_nodejs_wrapper(&wasm_dir, &config.circuit_name)?;

    println!("WASM witness calculator generated successfully!");
    println!("Generated files in: {}", wasm_dir.display());
    println!("Import from: {}/pkg/", wasm_dir.display());
    println!("Test with: node {}/generate_witness.js", wasm_dir.display());

    Ok(())
}

fn create_wasm_crate_structure(wasm_dir: &PathBuf) -> Result<(), WasmError> {
    fs::create_dir_all(wasm_dir)?;
    fs::create_dir_all(wasm_dir.join("src"))?;

    println!("Created WASM crate structure");
    Ok(())
}

fn validate_r1cs_data(r1cs_data: &[u8]) -> Result<(), WasmError> {
    if r1cs_data.len() < 8 {
        return Err(WasmError::R1csError("R1CS file too small".to_string()));
    }

    if &r1cs_data[0..8] != b"lof-r1cs" {
        return Err(WasmError::R1csError(
            "Invalid magic bytes - not a lof-r1cs file".to_string(),
        ));
    }

    println!("✅ R1CS file validation passed ({} bytes)", r1cs_data.len());
    Ok(())
}

fn generate_cargo_toml(wasm_dir: &Path, circuit_name: &str) -> Result<(), WasmError> {
    let cargo_toml = format!(
        r#"[package]
name = "{}_witness_calculator"
version = "0.1.0"
edition = "2021"
description = "WASM witness calculator for {} circuit generated by Lof"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
ark-bn254 = "0.4"
ark-ff = "0.4"
serde = {{ version = "1.0", features = ["derive"] }}
serde_json = "1.0"
console_error_panic_hook = {{ version = "0.1", optional = true }}
wee_alloc = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]

[features]
default = ["console_error_panic_hook"]

[profile.release]
opt-level = "s"
lto = true
debug = false
"#,
        circuit_name.to_lowercase(),
        circuit_name
    );

    let cargo_path = wasm_dir.join("Cargo.toml");
    fs::write(&cargo_path, cargo_toml)?;

    println!("Generated Cargo.toml at: {}", cargo_path.display());

    Ok(())
}

fn generate_lib_rs(wasm_dir: &Path, circuit_name: &str) -> Result<(), WasmError> {
    let lib_rs = format!(
        r#"//! WASM witness calculator for {} circuit
//! Generated by Lof compiler

mod r1cs_types;
mod solver;
mod embedded_r1cs;

use wasm_bindgen::prelude::*;
use ark_bn254::Fr;
use serde_json::{{Value, Map}};
use r1cs_types::ConstraintSystem;
use solver::generate_full_witness;
use embedded_r1cs::get_embedded_r1cs;

// Set up panic hook for better error messages in browser
#[cfg(feature = "console_error_panic_hook")]
#[wasm_bindgen(start)]
pub fn main() {{
    console_error_panic_hook::set_once();
}}

// Use wee_alloc as the global allocator for smaller WASM size
#[global_allocator]
static ALLOC: wee_alloc::WeeAlloc = wee_alloc::WeeAlloc::INIT;

/// Main witness calculator for {} circuit
#[wasm_bindgen]
pub struct WitnessCalculator {{
    constraint_system: ConstraintSystem,
}}

#[wasm_bindgen]
impl WitnessCalculator {{
    /// Create a new witness calculator instance
    #[wasm_bindgen(constructor)]
    pub fn new() -> Result<WitnessCalculator, JsValue> {{
        let r1cs_data = get_embedded_r1cs();
        let constraint_system = parse_embedded_r1cs(&r1cs_data)
            .map_err(|e| JsValue::from_str(&format!("Failed to parse R1CS: {{}}", e)))?;
        
        Ok(WitnessCalculator {{
            constraint_system,
        }})
    }}
        /// Debug function to inspect the constraint system
        #[wasm_bindgen]
        pub fn debug_constraint_info(&self) -> String {{
            let first_constraint_info = if !self.constraint_system.constraints.is_empty() {{
                let c = &self.constraint_system.constraints[0];
                format!("A: {{:?}}, B: {{:?}}, C: {{:?}}", c.a.terms, c.b.terms, c.c.terms)
    }} else {{
            "No constraints".to_string()
    }};
        
        format!(
            "Constraints: {{}}, Public: {{}}, Witnesses: {{}}\nFirst constraint: {{}}",
            self.constraint_system.constraints.len(),
            self.constraint_system.public_inputs.len(), 
            self.constraint_system.witnesses.len(),
            first_constraint_info
        )
}}
    
    /// Calculate witness from inputs JSON string
    /// 
    /// # Arguments
    /// * `inputs_json` - JSON string with circuit inputs, e.g. '{{"x": "42"}}'
    /// 
    /// # Returns
    /// JSON string with witness array, e.g. '["43", "123"]'
    #[wasm_bindgen]
    pub fn calculate_witness(&self, inputs_json: &str) -> Result<String, JsValue> {{
        // Parse JSON inputs
        let inputs: Map<String, Value> = serde_json::from_str(inputs_json)
            .map_err(|e| JsValue::from_str(&format!("Invalid JSON: {{}}", e)))?;
        
        // Convert inputs to field elements
        let mut field_inputs = Vec::new();
        for pub_input_name in &self.constraint_system.public_inputs {{
            if let Some(input_value) = inputs.get(pub_input_name) {{
                let field_val = parse_field_value(input_value)
                    .map_err(|e| JsValue::from_str(&format!("Invalid input '{{}}': {{}}", pub_input_name, e)))?;
                field_inputs.push(field_val);
            }} else {{
                return Err(JsValue::from_str(&format!("Missing required input: {{}}", pub_input_name)));
            }}
        }}
        
        // Generate witness using constraint solver
        let witness = generate_full_witness(&self.constraint_system, &field_inputs)
            .map_err(|e| JsValue::from_str(&format!("Witness generation failed: {{}}", e)))?;
        
        // Convert witness to JSON array of strings
        let witness_strings: Vec<String> = witness.iter()
            .map(|w| field_to_string(w))
            .collect();
        
        serde_json::to_string(&witness_strings)
            .map_err(|e| JsValue::from_str(&format!("JSON serialization failed: {{}}", e)))
    }}
    
    /// Get the circuit name
    #[wasm_bindgen]
    pub fn get_circuit_name(&self) -> String {{
        "{}".to_string()
    }}
    
    /// Get number of constraints in the circuit
    #[wasm_bindgen]
    pub fn get_constraint_count(&self) -> usize {{
        self.constraint_system.constraints.len()
    }}
    
    /// Get number of public inputs
    #[wasm_bindgen]
    pub fn get_public_input_count(&self) -> usize {{
        self.constraint_system.public_inputs.len()
    }}
    
    /// Get number of witness variables
    #[wasm_bindgen]
    pub fn get_witness_count(&self) -> usize {{
        self.constraint_system.witnesses.len()
    }}
    
    /// Get public input names as JSON array
    #[wasm_bindgen]
    pub fn get_public_input_names(&self) -> String {{
        serde_json::to_string(&self.constraint_system.public_inputs).unwrap_or_default()
    }}
    
    /// Debug function to test witness generation without string conversion
    #[wasm_bindgen]
    pub fn debug_calculate_witness(&self, inputs_json: &str) -> Result<u32, JsValue> {{
        // Parse JSON inputs
        let inputs: Map<String, Value> = serde_json::from_str(inputs_json)
            .map_err(|e| JsValue::from_str(&format!("Invalid JSON: {{}}", e)))?;
        
        // Convert inputs to field elements
        let mut field_inputs = Vec::new();
        for pub_input_name in &self.constraint_system.public_inputs {{
            if let Some(input_value) = inputs.get(pub_input_name) {{
                let field_val = parse_field_value(input_value)
                    .map_err(|e| JsValue::from_str(&format!("Invalid input '{{}}': {{}}", pub_input_name, e)))?;
                field_inputs.push(field_val);
            }} else {{
                return Err(JsValue::from_str(&format!("Missing required input: {{}}", pub_input_name)));
            }}
        }}
        
        // Generate witness using constraint solver
        let witness = generate_full_witness(&self.constraint_system, &field_inputs)
            .map_err(|e| JsValue::from_str(&format!("Witness generation failed: {{}}", e)))?;
        
        // Just return the witness count instead of converting to strings
        Ok(witness.len() as u32)
    }}
    
    #[wasm_bindgen]
    pub fn get_circuit_info(&self) -> String {{
        let info = serde_json::json!({{
            "circuit_name": "{}",
            "constraint_count": self.constraint_system.constraints.len(),
            "public_input_count": self.constraint_system.public_inputs.len(),
            "witness_count": self.constraint_system.witnesses.len(),
            "public_inputs": self.constraint_system.public_inputs
        }});
        info.to_string()
    }}
}}

fn parse_field_value(value: &Value) -> Result<Fr, String> {{
    match value {{
        Value::String(s) => {{
            // Try to parse as decimal string first
            if let Ok(num) = s.parse::<u64>() {{
                return Ok(Fr::from(num));
            }}
            
            // Try to parse as hex string
            if s.starts_with("0x") {{
                if let Ok(num) = u64::from_str_radix(&s[2..], 16) {{
                    return Ok(Fr::from(num));
                }}
            }}
            
            // Try to parse as large decimal string using ark-ff
            // This is a simplified version - full implementation would handle arbitrary precision
            Err(format!("Cannot parse '{{}}' as field element", s))
        }}
        Value::Number(n) => {{
            if let Some(i) = n.as_u64() {{
                Ok(Fr::from(i))
            }} else {{
                Err("Number too large for field element".to_string())
            }}
        }}
        _ => Err("Field value must be string or number".to_string())
    }}
}}

fn field_to_string(field: &Fr) -> String {{
    // Convert field element to decimal string representation
    // This is a simplified version - in practice you might want more sophisticated conversion
    format!("{{}}", field)
}}

fn parse_embedded_r1cs(r1cs_data: &[u8]) -> Result<ConstraintSystem, String> {{
    ConstraintSystem::from_bytes(r1cs_data)
        .map_err(|e| format!("R1CS parsing error: {{}}", e))
}}
"#,
        circuit_name, circuit_name, circuit_name, circuit_name
    );

    let lib_path = wasm_dir.join("src").join("lib.rs");
    fs::write(lib_path, lib_rs)?;

    println!("Generated lib.rs");
    Ok(())
}

fn embed_r1cs_data(wasm_dir: &Path, r1cs_data: &[u8]) -> Result<(), WasmError> {
    let mut embedded_rs = String::new();
    embedded_rs.push_str("//! Embedded R1CS data\n//! Generated by Lof compiler\n\n");
    embedded_rs.push_str("/// Get the embedded R1CS constraint system data\n");
    embedded_rs.push_str("pub fn get_embedded_r1cs() -> &'static [u8] {\n");
    embedded_rs.push_str("    &[\n");

    // Write bytes in chunks of 16 for readability
    for (i, byte) in r1cs_data.iter().enumerate() {
        if i % 16 == 0 {
            embedded_rs.push_str("        ");
        }
        embedded_rs.push_str(&format!("0x{:02x}, ", byte));
        if i % 16 == 15 {
            embedded_rs.push('\n');
        }
    }

    if r1cs_data.len() % 16 != 0 {
        embedded_rs.push('\n');
    }

    embedded_rs.push_str("    ]\n");
    embedded_rs.push_str("}\n\n");
    embedded_rs.push_str("/// Size of embedded R1CS data in bytes\n");
    embedded_rs.push_str(&format!(
        "pub const R1CS_SIZE: usize = {};\n",
        r1cs_data.len()
    ));

    let embedded_path = wasm_dir.join("src").join("embedded_r1cs.rs");
    fs::write(embedded_path, embedded_rs)?;

    println!("Embedded R1CS data ({} bytes)", r1cs_data.len());
    Ok(())
}

fn generate_solver(wasm_dir: &Path) -> Result<(), WasmError> {
    let solver_rs = r#"//! Constraint solver logic for witness generation
//! Ported from lofit library

use ark_bn254::Fr;
use ark_ff::Field;
use std::collections::HashMap;
use crate::r1cs_types::ConstraintSystem;

/// Generate full witness from public inputs using constraint satisfaction
/// 
/// This function iteratively solves R1CS constraints to compute all witness values.
/// It uses a simple constraint propagation algorithm that repeatedly evaluates
/// constraints until all witness variables are determined.
pub fn generate_full_witness(
    r1cs: &ConstraintSystem,
    pub_inputs: &[Fr],
) -> Result<Vec<Fr>, Box<dyn std::error::Error>> {
    let mut values = HashMap::new();
    
    // Add ONE constant (always at index 0)
    values.insert(0u32, Fr::from(1u64));
    
    // Add public inputs (starting at index 1)
    for (i, val) in pub_inputs.iter().enumerate() {
        values.insert((i + 1) as u32, *val);
    }
    
    // Calculate all witness values by evaluating constraints iteratively
    let mut changed = true;
    let mut iterations = 0;
    const MAX_ITERATIONS: usize = 100; // Prevent infinite loops
    
    while changed && iterations < MAX_ITERATIONS {
        changed = false;
        iterations += 1;
        
        for constraint in &r1cs.constraints {
            // Skip constraints we can't fully evaluate yet
            if !can_evaluate_terms(&constraint.a.terms, &values) || 
               !can_evaluate_terms(&constraint.b.terms, &values) {
                continue;
            }
                
            // Only consider constraints where C is a single term we don't know yet
            if constraint.c.terms.len() == 1 {
                let (c_var, c_coeff) = constraint.c.terms[0];
                if !values.contains_key(&c_var) {
                    // Calculate A * B = C
                    let mut a_val = Fr::from(0u64);
                    for (a_var, a_coeff) in &constraint.a.terms {
                        a_val += values[a_var] * Fr::from(*a_coeff as u64);
                    }
                    
                    let mut b_val = Fr::from(0u64);
                    for (b_var, b_coeff) in &constraint.b.terms {
                        b_val += values[b_var] * Fr::from(*b_coeff as u64);
                    }
                    
                    let c_val = a_val * b_val;
                    
                    // Adjust for coefficient: c_coeff * c_var = c_val
                    if c_coeff != 1 {
                        let inv_coeff = Fr::from(c_coeff as u64).inverse()
                            .ok_or("Cannot invert coefficient")?;
                        values.insert(c_var, c_val * inv_coeff);
                    } else {
                        values.insert(c_var, c_val);
                    }
                    
                    changed = true;
                }
            }
        }
    }
    
    if iterations == MAX_ITERATIONS {
        return Err("Failed to calculate all witness values - maximum iterations exceeded".into());
    }
    
    // Find the maximum variable index to determine witness size
    let max_var = *values.keys().max().unwrap_or(&0);
    
    let mut witness = Vec::new();
    // Skip the public inputs (including ONE), collect only witness variables
    for i in (pub_inputs.len() + 1) as u32..=max_var {
        // Debug: let's see what variables we're looking for
        if !values.contains_key(&i) {
            // If we don't have a value for this variable, that's the problem
            return Err(format!("Missing value for witness variable {} (max_var: {}, values: {:?})", i, max_var, values.keys().collect::<Vec<_>>()).into());
        }
        if let Some(val) = values.get(&i) {
            witness.push(*val);
        }
    }
    
    Ok(witness)
}

/// Check if all terms in a linear combination can be evaluated
fn can_evaluate_terms(terms: &[(u32, i64)], values: &HashMap<u32, Fr>) -> bool {
    terms.iter().all(|(var, _)| values.contains_key(var))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::r1cs_types::{Constraint, LinearCombination};

    #[test]
    fn test_simple_witness_generation() {
        // Test with a simple constraint: x * 1 = x (identity)
        let constraint = Constraint {
            a: LinearCombination { terms: vec![(1, 1)] }, // x
            b: LinearCombination { terms: vec![(0, 1)] }, // ONE
            c: LinearCombination { terms: vec![(1, 1)] }, // x
        };
        
        let r1cs = ConstraintSystem {
            public_inputs: vec!["x".to_string()],
            witnesses: vec![],
            constraints: vec![constraint],
        };
        
        let pub_inputs = vec![Fr::from(42u64)];
        let witness = generate_full_witness(&r1cs, &pub_inputs).unwrap();
        
        // Should be empty since x is a public input, not a witness
        assert_eq!(witness.len(), 0);
    }
}
"#;

    let solver_path = wasm_dir.join("src").join("solver.rs");
    fs::write(solver_path, solver_rs)?;

    println!("Generated solver.rs");
    Ok(())
}

fn generate_r1cs_types(wasm_dir: &Path) -> Result<(), WasmError> {
    let r1cs_types = r#"//! R1CS types and parsing logic
//! Compatible with Lof compiler R1CS format

use std::io::{self, Read};

/// R1CS constraint system containing circuit information
#[derive(Debug, Clone)]
pub struct ConstraintSystem {
    /// Names of public input signals
    pub public_inputs: Vec<String>,
    /// Names of witness (private) signals  
    pub witnesses: Vec<String>,
    /// R1CS constraints (A * B = C format)
    pub constraints: Vec<Constraint>,
}

/// Single R1CS constraint: A * B = C
#[derive(Debug, Clone)]
pub struct Constraint {
    pub a: LinearCombination,
    pub b: LinearCombination,
    pub c: LinearCombination,
}

/// Linear combination of variables with coefficients
#[derive(Debug, Clone)]
pub struct LinearCombination {
    /// Vector of (variable_index, coefficient) pairs
    pub terms: Vec<(u32, i64)>,
}

impl ConstraintSystem {
    /// Parse constraint system from byte array
    pub fn from_bytes(data: &[u8]) -> io::Result<Self> {
        let mut reader = std::io::Cursor::new(data);
        Self::from_reader(&mut reader)
    }
    
    /// Parse constraint system from reader
    pub fn from_reader(mut reader: impl Read) -> io::Result<Self> {
        // Read and verify magic bytes
        let mut magic = [0u8; 8];
        reader.read_exact(&mut magic)?;
        if &magic != b"lof-r1cs" {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "Invalid magic bytes - not a lof-r1cs file"
            ));
        }

        // Read and verify version
        let mut version = [0u8; 4];
        reader.read_exact(&mut version)?;
        if u32::from_le_bytes(version) != 1 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "Unsupported r1cs version"
            ));
        }

        let mut buf = [0u8; 4];
        
        // Read counts
        reader.read_exact(&mut buf)?;
        let pub_inputs_count = u32::from_le_bytes(buf);
        
        reader.read_exact(&mut buf)?;
        let witnesses_count = u32::from_le_bytes(buf);
        
        reader.read_exact(&mut buf)?;
        let constraints_count = u32::from_le_bytes(buf);

        // Read public input names
        let mut public_inputs = Vec::new();
        for _ in 0..pub_inputs_count {
            reader.read_exact(&mut buf)?;
            let len = u32::from_le_bytes(buf) as usize;
            let mut name = vec![0u8; len];
            reader.read_exact(&mut name)?;
            public_inputs.push(String::from_utf8(name)
                .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?);
        }

        // Read witness names
        let mut witnesses = Vec::new();
        for _ in 0..witnesses_count {
            reader.read_exact(&mut buf)?;
            let len = u32::from_le_bytes(buf) as usize;
            let mut name = vec![0u8; len];
            reader.read_exact(&mut name)?;
            witnesses.push(String::from_utf8(name)
                .map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))?);
        }

        // Read constraints
        let mut constraints = Vec::new();
        for _ in 0..constraints_count {
            let a = read_linear_combination(&mut reader)?;
            let b = read_linear_combination(&mut reader)?;
            let c = read_linear_combination(&mut reader)?;
            constraints.push(Constraint { a, b, c });
        }

        Ok(Self {
            public_inputs,
            witnesses,
            constraints,
        })
    }
    
    /// Get total number of variables (public inputs + witnesses + ONE)
    pub fn get_variable_count(&self) -> usize {
        1 + self.public_inputs.len() + self.witnesses.len() // +1 for ONE
    }
}

/// Read a linear combination from binary format
fn read_linear_combination(reader: &mut impl Read) -> io::Result<LinearCombination> {
    let mut buf = [0u8; 4];
    reader.read_exact(&mut buf)?;
    let terms_count = u32::from_le_bytes(buf);
    
    let mut terms = Vec::new();
    for _ in 0..terms_count {
        // Read variable index
        reader.read_exact(&mut buf)?;
        let var_idx = u32::from_le_bytes(buf);
        
        // Read coefficient  
        let mut coeff_buf = [0u8; 8];
        reader.read_exact(&mut coeff_buf)?;
        let coeff = i64::from_le_bytes(coeff_buf);
        
        // Debug: Check if we're getting reasonable values
        if var_idx > 100 {  // Sanity check
            eprintln!("WARNING: Suspicious variable index: {}", var_idx);
        }
        
        terms.push((var_idx, coeff));
    }
    
    Ok(LinearCombination { terms })
}

impl std::fmt::Display for Constraint {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "(")?;
        for (i, (var, coeff)) in self.a.terms.iter().enumerate() {
            if i > 0 { write!(f, " + ")?; }
            write!(f, "{}*v{}", coeff, var)?;
        }
        write!(f, ") * (")?;
        for (i, (var, coeff)) in self.b.terms.iter().enumerate() {
            if i > 0 { write!(f, " + ")?; }
            write!(f, "{}*v{}", coeff, var)?;
        }
        write!(f, ") = (")?;
        for (i, (var, coeff)) in self.c.terms.iter().enumerate() {
            if i > 0 { write!(f, " + ")?; }
            write!(f, "{}*v{}", coeff, var)?;
        }
        write!(f, ")")
    }
}
"#;

    let types_path = wasm_dir.join("src").join("r1cs_types.rs");
    fs::write(types_path, r1cs_types)?;

    println!("Generated r1cs_types.rs");
    Ok(())
}

fn build_wasm(wasm_dir: &PathBuf) -> Result<(), WasmError> {
    println!("Building WASM package with wasm-pack...");

    // Clean previous build
    let pkg_dir = wasm_dir.join("pkg");
    if pkg_dir.exists() {
        fs::remove_dir_all(&pkg_dir)?;
    }

    // Make sure we're not in a workspace by checking for Cargo.lock and Cargo.toml in parent dirs
    let output = Command::new("wasm-pack")
        .args(["build", "--target", "web", "--out-dir", "pkg", "--release"])
        .current_dir(wasm_dir)
        .env("CARGO_TARGET_DIR", wasm_dir.join("target")) // Isolate build
        .output()
        .map_err(|e| WasmError::CommandFailed(format!("Failed to execute wasm-pack: {}", e)))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let stdout = String::from_utf8_lossy(&output.stdout);

        return Err(WasmError::BuildFailed(format!(
            "wasm-pack build failed:\nSTDOUT: {}\nSTDERR: {}",
            stdout, stderr
        )));
    }

    println!("✅ WASM build completed successfully");
    Ok(())
}

fn generate_nodejs_wrapper(wasm_dir: &Path, circuit_name: &str) -> Result<(), WasmError> {
    let wrapper_js = format!(
        r#"#!/usr/bin/env node
/**
 * Node.js witness calculator for {} circuit
 * Similar to Circom's generate_witness.js
 * 
 * Usage: node generate_witness.js <input.json> [output.json]
 */

const fs = require('fs');
const path = require('path');

// Import the WASM module
async function loadWasm() {{
    const wasmModule = await import('./pkg/{}_witness_calculator.js');
    await wasmModule.default(); // Initialize WASM
    return wasmModule;
}}

async function generateWitness(inputFile, outputFile) {{
    try {{
        // Load WASM module
        const wasm = await loadWasm();
        
        // Read input file
        if (!fs.existsSync(inputFile)) {{
            throw new Error(`Input file not found: ${{inputFile}}`);
        }}
        
        const inputData = fs.readFileSync(inputFile, 'utf8');
        console.log(`📖 Reading inputs from: ${{inputFile}}`);
        
        // Create witness calculator
        const calculator = new wasm.WitnessCalculator();
        
        // Print circuit info
        const info = JSON.parse(calculator.get_circuit_info());
        console.log(`🔧 Circuit: ${{info.circuit_name}}`);
        console.log(`📊 Constraints: ${{info.constraint_count}}`);
        console.log(`🔍 Public inputs: ${{info.public_input_count}}`);
        console.log(`🔒 Witnesses: ${{info.witness_count}}`);
        
        // Calculate witness
        console.log(`⚡ Calculating witness...`);
        const witnessJson = calculator.calculate_witness(inputData);
        const witness = JSON.parse(witnessJson);
        
        console.log(`✅ Witness calculated successfully!`);
        console.log(`📏 Witness size: ${{witness.length}} elements`);
        
        // Write output
        if (outputFile) {{
            fs.writeFileSync(outputFile, JSON.stringify(witness, null, 2));
            console.log(`💾 Witness saved to: ${{outputFile}}`);
        }} else {{
            console.log(`📄 Witness:`);
            console.log(JSON.stringify(witness, null, 2));
        }}
        
    }} catch (error) {{
        console.error(`❌ Error: ${{error.message}}`);
        process.exit(1);
    }}
}}

// Parse command line arguments
function main() {{
    const args = process.argv.slice(2);
    
    if (args.length === 0 || args.includes('--help') || args.includes('-h')) {{
        console.log(`
{} Circuit Witness Calculator

Usage:
    node generate_witness.js <input.json> [output.json]
    
Arguments:
    input.json    JSON file with circuit inputs
    output.json   Optional output file (prints to console if not specified)
    
Examples:
    node generate_witness.js input.json
    node generate_witness.js input.json witness.json
        `);
        return;
    }}
    
    const inputFile = args[0];
    const outputFile = args[1];
    
    generateWitness(inputFile, outputFile);
}}

// Run if called directly
if (require.main === module) {{
    main();
}}

module.exports = {{ generateWitness }};
"#,
        circuit_name,
        circuit_name.to_lowercase(),
        circuit_name
    );

    let wrapper_path = wasm_dir.join("generate_witness.js");
    fs::write(wrapper_path, wrapper_js)?;

    // Make it executable on Unix systems
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let gen_witness_path = wasm_dir.join("generate_witness.js");
        let mut perms = fs::metadata(&gen_witness_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(gen_witness_path, perms)?;
    }

    // Generate a simple browser example
    generate_browser_example(wasm_dir, circuit_name)?;

    println!("Generated Node.js wrapper and browser example");
    Ok(())
}

fn generate_browser_example(wasm_dir: &Path, circuit_name: &str) -> Result<(), WasmError> {
    let example_html = format!(
        r#"<!DOCTYPE html>
<html>
<head>
    <title>{} Circuit - WASM Witness Calculator</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }}
        .container {{
            background: #f5f5f5;
            padding: 20px;
            border-radius: 8px;
            margin: 10px 0;
        }}
        textarea {{
            width: 100%;
            height: 100px;
            font-family: monospace;
        }}
        button {{
            background: #007cba;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 4px;
            cursor: pointer;
        }}
        button:hover {{
            background: #005a87;
        }}
        .result {{
            background: white;
            padding: 15px;
            border-radius: 4px;
            border-left: 4px solid #007cba;
            white-space: pre-wrap;
            font-family: monospace;
        }}
        .error {{
            border-left-color: #dc3545;
            background: #fff5f5;
        }}
    </style>
</head>
<body>
    <h1>{} Circuit - WASM Witness Calculator</h1>
    
    <div class="container">
        <h3>Circuit Information</h3>
        <div id="circuit-info">Loading...</div>
    </div>
    
    <div class="container">
        <h3>Input JSON</h3>
        <textarea id="input-json" placeholder='Enter circuit inputs, e.g.: {{"x": "42"}}'>{}</textarea>
        <br><br>
        <button onclick="calculateWitness()">Calculate Witness</button>
    </div>
    
    <div class="container">
        <h3>Result</h3>
        <div id="result" class="result">Click "Calculate Witness" to generate witness...</div>
    </div>

    <script type="module">
        import init, {{ WitnessCalculator }} from './pkg/{}_witness_calculator.js';
        
        let calculator = null;
        
        async function initWasm() {{
            try {{
                await init();
                calculator = new WitnessCalculator();
                
                // Display circuit info
                const info = JSON.parse(calculator.get_circuit_info());
                document.getElementById('circuit-info').innerHTML = `
                    <strong>Circuit:</strong> ${{info.circuit_name}}<br>
                    <strong>Constraints:</strong> ${{info.constraint_count}}<br>
                    <strong>Public Inputs:</strong> ${{info.public_input_count}}<br>
                    <strong>Witnesses:</strong> ${{info.witness_count}}<br>
                    <strong>Required Inputs:</strong> ${{info.public_inputs.join(', ')}}
                `;
            }} catch (error) {{
                document.getElementById('circuit-info').innerHTML = `
                    <span style="color: red;">Error loading WASM: ${{error.message}}</span>
                `;
            }}
        }}
        
        window.calculateWitness = async function() {{
            const resultDiv = document.getElementById('result');
            const inputJson = document.getElementById('input-json').value;
            
            if (!calculator) {{
                resultDiv.className = 'result error';
                resultDiv.textContent = 'WASM not initialized. Please refresh the page.';
                return;
            }}
            
            try {{
                resultDiv.className = 'result';
                resultDiv.textContent = 'Calculating witness...';
                
                const witnessJson = calculator.calculate_witness(inputJson);
                const witness = JSON.parse(witnessJson);
                
                resultDiv.textContent = `Witness calculated successfully!

Witness (${{witness.length}} elements):
${{JSON.stringify(witness, null, 2)}}`;
                
            }} catch (error) {{
                resultDiv.className = 'result error';
                resultDiv.textContent = `Error: ${{error.message}}`;
            }}
        }}
        
        // Initialize when page loads
        initWasm();
    </script>
</body>
</html>
"#,
        circuit_name,
        circuit_name,
        r#"{"x": "42"}"#,
        circuit_name.to_lowercase()
    );

    let example_path = wasm_dir.join("example.html");
    fs::write(example_path, example_html)?;

    Ok(())
}
